app_launch_prefix = ""
terminal_title_flag = ""
locale = ""
close_when_open = false
theme = "hypr"
monitor = ""
hotreload_theme = false
as_window = false
timeout = 0
terminal = "kitty"
disable_click_to_close = false
force_keyboard_focus = false
disabled = [
    "runner",
    "bookmarks"
]

[shell]
anchor_top = true
anchor_bottom = true
anchor_left = true
anchor_right = true

[placeholders]
"default" = { input = "Search", list = "No Results" } # placeholders for input and empty list, key is the providers name, so f.e. "desktopapplications" or "menus:other"

[keybinds]
close = ["Escape"]
next = ["Down"]
previous = ["Up"]
toggle_exact = ["ctrl e"]
resume_last_query = ["ctrl r"]

[providers]
default = [
  "desktopapplications",
  "calc",
  "runner",
  "menus",
  "websearch"
] # providers to be queried by default
empty = ["desktopapplications"] # providers to be queried when query is empty

[[providers.prefixes]]
prefix = ";"
provider = "providerlist"

[[providers.prefixes]]
prefix = "/"
provider = "files"

[[providers.prefixes]]
prefix = "."
provider = "symbols"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = ":"
provider = "clipboard"

[providers.calc]
click = "copy"
copy = "Return"
save = "ctrl s"
delete = "ctrl d"

[providers.websearch]
click = "search"
search = "Return"

[providers.providerlist]
click = "activate"
activate = "Return"

[providers.clipboard]
time_format = "%d.%m. - %H:%M" # format for the clipboard item date
click = "copy"
copy = "Return"
delete = "ctrl d"

[providers.desktopapplications]
click = "start"
start = "Return"

[providers.files]
click = "open"
open = "Return"
open_dir = "ctrl Return"
copy_path = "ctrl shift C"
copy_file = "ctrl c"

[providers.runner]
click = "start"
start = "Return"
start_terminal = "shift Return"

[providers.dmenu]
click = "select"
select = "Return"

[providers.symbols]
click = "copy"
copy = "Return"

[providers.menus]
click = "activate"
activate = "Return"
